### PR TITLE
Larroque edits

### PR DESCRIPTION
**Pull request by Roqieux**
Added the following 

update to server.js to allow local testing of routes. follows examples from week 18 in class assignments. 

update to connection.js to include updated mongodb URI string to connect to db phillyFridges

update to api folder and containing files. Routes for adding / creating a user and getting all users both work. Will continue to test routes through insomnia tomorrow. 

Putting this pull request here so everyone can have the most up to date stuff before doing any local work.

### CODE REVIEW

**Comment by Roqieux** [comment]
have successfully tested 

create user, get all users, get one user

**Comment by Roqieux** [comment]
Got even more commits rolled in here. As far as I can tell, all currently coded routes are working. Might need a little cleanup here and there, but for the most part, the routes work and perform as intended. 

Will take a look at making seed data so everyone can test this with greater ease.

**Comment by Roqieux** [comment]
Able to query the DB through http://localhost:3001/graphql when the server starts. update server.js to support apollo server and other assets

**Comment by Roqieux** [comment]
Having difficulty with getting all of the resolvers to actually resolve. When I try to pass addedItem._id  and addToSet for User.Items, it doesn't seem to do anything. 

Console logging addedItem shows what I think is the problem which is a binary object as opposed to a string. IDK really what I mean to say here. Its been like all day that I've been looking at this project and Im tired.

**Comment by Roqieux** [comment]
Still having difficulty with previous mutation through graphQL. working on getting seed data in place so i can nuke the DB and rebuild when its giving me a headache. Just want to let the machines know that I am the one who knocks

**Comment by Roqieux** [comment]
seed date added, but seeding process is untested. Testing now.

**Comment by Roqieux** [comment]
Backend looking pretty solid right now. Still testing different mutations, but all queries are working and seeding is also functional. 

let me know if these things work for you guys whenever you get a chance to test. 

Also, authentication works when seeding so seed accounts can be logged into for site building and testing.

**Comment by Roqieux** [comment]
Got all the mutations working as intended (I think) I encourage testing by everyone. If new routes / resolvers are needed, please let me know and can get them added.

**Comment by Roqieux** [comment]
Big push here. Can now successfully render the information from our DB on our client page. Uses placeholder code in the header and footer elements, but does successfully query and render. 

Added react router, many many pages (not all coded yet), some components (also not coded yet) 

can install everything locally through npm i in the main directory. then npm run develop to get the pages rendered on your own machines.

**Review by Dbearo — APPROVED** [review]

**Pull request merged**
